#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
DEPRECATED - 2026 MIGRATION

This script has been replaced by qdrant-semantic-search.py with --hybrid flag.
New queries should use universal_vault collection with hybrid search.

For migration details, see ~/.claude/MIGRATION_STATE.md

---

An improved Python script for querying a Qdrant collection via its REST API.

Features:
- Query by collection name.
- Filter results by topic (exact match) or tags.
- Perform keyword search within the 'content' payload field.
- List all items in a collection.
- Control output format: full details, summary only, or content only.
- Colorized output for improved readability in a terminal.
- Connects to a Qdrant instance on localhost:6333.

Generated by Gemini via the self-improvement loop.
"""

import argparse
import requests
import json
import sys

# ANSI color codes for terminal output
class Colors:
    """A class to hold ANSI color codes for terminal output."""
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    CYAN = '\033[96m'

def print_point(point, args):
    """
    Prints a single Qdrant point with formatting based on command-line arguments.

    Args:
        point (dict): The Qdrant point object from the API response.
        args (argparse.Namespace): The parsed command-line arguments.
    """
    payload = point.get('payload', {})
    if not payload:
        return

    # If --content-only is specified, print only the content and exit
    if args.content_only:
        print(payload.get('content', ''))
        return

    topic = payload.get('topic', 'N/A')
    summary = payload.get('summary', 'N/A')

    # Print a separator and the main identifier for the result
    print(f"{Colors.BOLD}{Colors.YELLOW}--- Result (ID: {point['id']}) ---{Colors.ENDC}")
    print(f"{Colors.BOLD}{Colors.CYAN}Topic:{Colors.ENDC} {topic}")
    print(f"{Colors.BOLD}{Colors.CYAN}Summary:{Colors.ENDC}\n{Colors.GREEN}{summary}{Colors.ENDC}")

    # If not in summary-only mode, print the rest of the details
    if not args.summary_only:
        content = payload.get('content', 'N/A')
        tags = payload.get('tags', [])
        tag_str = ', '.join(map(str, tags)) if tags else 'None'

        print(f"{Colors.BOLD}{Colors.CYAN}Tags:{Colors.ENDC} {tag_str}")
        print(f"{Colors.BOLD}{Colors.CYAN}Content:{Colors.ENDC}\n{content}")

    # Print a final separator for clarity between results
    print("\n" + "="*80 + "\n")

def main():
    """
    Main function to parse arguments, build the Qdrant query, execute it,
    and print the results.
    """
    parser = argparse.ArgumentParser(
        description="Query a Qdrant collection with filtering and formatting options.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "--collection",
        type=str,
        required=True,
        help="Name of the Qdrant collection to query."
    )
    parser.add_argument(
        "--topic",
        type=str,
        help="Filter for an exact match on the 'topic' payload field."
    )
    parser.add_argument(
        "--tags",
        type=str,
        help="Filter by comma-separated tags. Matches if any tag is present."
    )
    parser.add_argument(
        "--search",
        type=str,
        help="Perform a keyword search in the 'content' payload field."
    )
    parser.add_argument(
        "--list-all",
        action="store_true",
        help="List all documents, ignoring other filters."
    )
    parser.add_argument(
        "--summary-only",
        action="store_true",
        help="Show only the topic and summary for each result."
    )
    parser.add_argument(
        "--content-only",
        action="store_true",
        help="Extract and print only the 'content' field, for piping."
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=10,
        help="The maximum number of results to return."
    )

    args = parser.parse_args()

    qdrant_url = f"http://localhost:6333/collections/{args.collection}/points/scroll"
    headers = {'Content-Type': 'application/json'}

    filter_conditions = []

    if not args.list_all:
        if args.topic:
            filter_conditions.append({
                "key": "topic",
                "match": {"value": args.topic}
            })
        if args.tags:
            tag_list = [tag.strip() for tag in args.tags.split(',')]
            filter_conditions.append({
                "key": "tags",
                "match": {"any": tag_list}
            })
        if args.search:
            filter_conditions.append({
                "key": "content",
                "match": {"text": args.search}
            })

    payload = {
        "with_payload": True,
        "with_vectors": False,
        "limit": args.limit
    }

    if filter_conditions:
        payload["filter"] = {"must": filter_conditions}

    try:
        response = requests.post(qdrant_url, headers=headers, data=json.dumps(payload), timeout=10)
        response.raise_for_status()

        data = response.json()
        points = data.get('result', {}).get('points', [])

        if not points:
            print(f"{Colors.YELLOW}No results found for your query.{Colors.ENDC}")
            return

        for point in points:
            print_point(point, args)

    except requests.exceptions.RequestException as e:
        print(f"{Colors.RED}Error connecting to Qdrant or executing query: {e}{Colors.ENDC}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError:
        print(f"{Colors.RED}Error: Failed to decode JSON response from Qdrant.{Colors.ENDC}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
